### ISSUE TITLE
Bump 2.2

### ISSUE THREAD

**Issue by f3l1x** [Markette/Gopay#48]
* [x] GoPay API completly standalone #34 
* [x] New GoPay inline method #45 
* [x] Possibility to change channel on gopay side #47
